### ISSUE TITLE
有固定列，拖拽标识显示错位

### ISSUE THREAD

**Issue by lhzhou180606** [hemengke1997/use-antd-resizable-header#10]

**Comment by hemengke1997** [comment]
给个复现吧老哥

**Comment by qinyang1018** [comment]
全部都设置width 标识就会错位

**Comment by hemengke1997** [comment]
> 全部都设置width 标识就会错位

不能全部设置width，受限于antd table本身的设计 https://ant-design.gitee.io/components/table-cn/#components-table-demo-fixed-columns
