### ISSUE TITLE
当表头为多级表头且有固定列时，非固定列被固定列完全遮挡

### ISSUE THREAD

**Issue by JIT-ChenXin** [hemengke1997/use-antd-resizable-header#11]
下图为正常情况：
![1](https://user-images.githubusercontent.com/26107204/156489454-640d4a24-85c8-43cb-8d27-a4765cc572ff.png)
下图为加入拖拽情况：
![image](https://user-images.githubusercontent.com/26107204/156489637-7536a101-4cbf-4b4f-8628-115cf750e95e.png)
下图为Table组件的props参数：
![image](https://user-images.githubusercontent.com/26107204/156489765-1611ff16-e03a-4f55-8951-1c06d7a1b1d5.png)

请问作者大大 有遇到这种情况吗

**Comment by hemengke1997** [comment]
可以给个复现吗

**Comment by JIT-ChenXin** [comment]
> 可以给个复现吗

我尝试在沙盒里复现，但没复现出来，只有本地存在这个问题，我明天调试一下源码

**Comment by hemengke1997** [comment]
好的，辛苦了。如果还是有问题的话，可以把columns，table发出来我看看
