### ISSUE TITLE
大佬 ProTable 设置宽度 偏位。

### ISSUE THREAD

**Issue by CHENJKNB** [hemengke1997/use-antd-resizable-header#15]
![image](https://user-images.githubusercontent.com/18523983/169194345-0f4d0088-d8f9-4efa-86ac-5f02d03a37ba.png)

**Comment by hemengke1997** [comment]
@CHENJKNB  columns配置发来看看呢

**Comment by CHENJKNB** [comment]
> @CHENJKNB columns配置发来看看呢

![image](https://user-images.githubusercontent.com/18523983/169196142-48606299-3598-4df7-82d5-22eae50cca7b.png)
![image](https://user-images.githubusercontent.com/18523983/169196183-726d544d-6154-41c5-8214-881a712370f2.png)

**Comment by CHENJKNB** [comment]
@hemengke1997  大佬 按照你的方法可以了。但是和标准的table 有点不不同，ProTable 拉伸会压缩最后一列的宽度 ，而Table不会，这个可以改进吗 ？谢谢！

**Comment by hemengke1997** [comment]
ProTable/Table 在拉伸的时候行为是一致的，会压缩没有设置宽度的列（优先级更高）或最后一列
