### ISSUE TITLE
tableWidth计算结果为0

### ISSUE THREAD

**Issue by acutbh** [hemengke1997/use-antd-resizable-header#16]
文件路径/useAntdResizableHeader.tsx 第175行
if (cls[i].hideInTable === false) {
建议更换为if (!cls[i].hideInTable) {

**Comment by hemengke1997** [comment]
这段代码是热心小伙伴提供的~ 如果可以的话你可以尝试提个pr

**Comment by zhb127** [comment]
> 文件路径/useAntdResizableHeader.tsx 第175行 if (cls[i].hideInTable === false) { 建议更换为if (!cls[i].hideInTable) {

抱歉抱歉，已按照 issue 建议进行调整。

项目里面没有出错，测试不够全面，后续只在 fork 仓库中更新，不再影响源仓库。

再次表示抱歉。
