### ISSUE TITLE
Columns变化时resizableColumns 不能及时更新

### ISSUE THREAD

**Issue by Song-aff** [hemengke1997/use-antd-resizable-header#18]

**Comment by hemengke1997** [comment]
方便贴一下代码吗？ 包括你定义的 `columns` 以及 `columns` 是如何触发改变的

**Comment by Song-aff** [comment]
const { components, resizableColumns, tableWidth } = useARH({
    columns: columns,
    columnsState: {
      persistenceKey: Key(),
      persistenceType: 'localStorage'
    }
  })
columns 变化时，resizableColumns不能随之更新

**Comment by Song-aff** [comment]
抱歉，我没注意到版本号，我先尝试升级下版本。

**Comment by Song-aff** [comment]
npm info 显示 当前库版本 为 latest: 2.1.3

**Comment by hemengke1997** [comment]
https://www.npmjs.com/package/@minko-fe/use-antd-resizable-header/v/2.4.0

**Comment by Song-aff** [comment]
感谢，已解决，回复效率点赞
