### ISSUE TITLE
请问为何要将开发依赖放置在peerDependency里？

### ISSUE THREAD

**Issue by lanzhi-lee** [hemengke1997/use-antd-resizable-header#19]
<img width="692" alt="image" src="https://user-images.githubusercontent.com/36190508/182842208-878b76cb-8a1b-43f9-a62c-873f81c03b92.png">
提这个问题的原因是，影响到了依赖安装

**Comment by hemengke1997** [comment]
我这边把这些去掉吧，其实这些依赖并不是开发依赖，我这边也是 `peerDependency`。
有个比较好使的方法：
`.npmrc`

```
strict-peer-dependencies=false
```

**Comment by hemengke1997** [comment]
fixed: https://github.com/hemengke1997/use-antd-resizable-header/commit/30545b03a266aecf4f5c2364038a4a9c103a93b0
