### ISSUE TITLE
有一列A 不设置宽度，拖拽其它列时，列A 宽度会被挤至0看不见，即最小宽度不生效

### ISSUE THREAD

**Issue by mtiger95** [hemengke1997/use-antd-resizable-header#20]
有一列A 不设置宽度，拖拽其它列时，列A 宽度会被挤至0看不见，即最小宽度不生效。
使用说明文档上面的那个链接打开就能看到，最后一列render看不到了。
https://codesandbox.io/s/silly-dream-rq89l?file=/src/App.tsx

**Comment by hemengke1997** [comment]
升级 `antd` 至 `4.23.0`
升级 `use-antd-resizable-header` 至 `2.4.1`

**Comment by hemengke1997** [comment]
codesandbox 依赖已更新，你可以再试试看
我试了一下没有出现 `width 为 0 的列消失` 的情况

**Comment by mtiger95** [comment]
> codesandbox 依赖已更新，你可以再试试看 我试了一下没有出现 `width 为 0 的列消失` 的情况

升级后问题已解决，感谢。

另外有个小发现：
1.当仅把第1列作为不设置宽度的列时，第1列宽度会远远超过120。
2.如果除了第1列，另外再任意一列(非最后一列)不设宽度，这两列宽度都会远远超过120.
3.如果除了第1列，再将最后一列不设宽度，此时能达到预期，第1 和最后一列默认宽度为120.

**Comment by hemengke1997** [comment]
方便给个复现吗？

**Comment by hemengke1997** [comment]
>  1.当仅把第1列作为不设置宽度的列时，第1列宽度会远远超过120。 

这是正常现象。不设宽度的列，会自然缩放，这是antd表格的问题。详见：https://ant-design.gitee.io/components/table-cn/#components-table-demo-fixed-columns

> 2.如果除了第1列，另外再任意一列(非最后一列)不设宽度，这两列宽度都会远远超过120.

这是不推荐的，原因同上。

> 3.如果除了第1列，再将最后一列不设宽度，此时能达到预期，第1 和最后一列默认宽度为120.

这是预期的现象。因为只有在一列不设宽度。

**Comment by hemengke1997** [comment]
只需要一列不设置宽度，非常不推荐多列不设置宽度。antd表格本身的缺陷导致的多列不设置宽度，多列都会自然改变宽度（去除其他列的宽度后成比例缩放）

**Comment by mtiger95** [comment]
![image](https://user-images.githubusercontent.com/23418622/188807873-d629493c-21e4-402f-a7eb-35de684fd7a2.png)
当仅把第1列作为不设置宽度的列时，第1列宽度会远远超过120。若是未出现滚动条，那么它自适应撑开宽度是正常的，但有滚动条时宽度应是120吧。

**Comment by hemengke1997** [comment]
> 当仅把第1列作为不设置宽度的列时，第1列宽度会远远超过120。若是未出现滚动条，那么它自适应撑开宽度是正常的，但有滚动条时宽度应是120吧。

这个理解不正确。
你大可抛开 `use-antd-resizable-header`， 单独使用 `antd` 的表格试试。（设置宽度即可复现你的想法）

仅第1列不设置宽度的话，第一列的最小宽度是120px，当滚动条宽度到达scroll.x的值时，第一列则展示为120px。否则自然放宽。

**Comment by mtiger95** [comment]
好的，明白了，谢谢回复。
