### ISSUE TITLE
可以考虑提供个钩子

### ISSUE THREAD

**Issue by henryzp** [hemengke1997/use-antd-resizable-header#21]
就是在拖拽列完成后，能有一个事件，参数是当前列的宽度，能让我ajax发起请求，保存到后端

简单地说，就是实现自定义列的功能，下次这个用户再次登录这个页面，某一列的宽度还是他最后一次改动的宽度

**Comment by hemengke1997** [comment]
有持久化拖拽宽度的选项，是否能满足你的需求呢

**Comment by henryzp** [comment]
额，必然不能啊。。。

像toB的项目，就是saas定制化的，每个人期望自己的table列宽可能都不一样的。。。我们之前用react-base-table有实现这样的功能，所以期望有这样的功能。。

那么我就可以放弃react-base-table了，转用antd的table，结合你的这个hooks，就完美了

**Comment by henryzp** [comment]
？？你的这个是存本地啊，我希望的是列拖完之后，能有个函数触发，告诉我当前列的宽度。然后我自己ajax请求去保存该用户对此列的宽度值发自我的手机-------- 原始邮件 --------发件人： hemengke1997 ***@***.***>日期： 2022年9月15日周四 下午4:22收件人： hemengke1997/use-antd-resizable-header ***@***.***>抄送： 小翼 ***@***.***>, Author ***@***.***>主    题： Re: [hemengke1997/use-antd-resizable-header] 可以考虑提供个钩子 (Issue #21)

我的理解 columnsState  选项是可以满足你的需求的，你可以看看

https://github.com/hemengke1997/use-antd-resizable-header/blob/master/src/useAntdResizableHeader.tsx#L17

如果满足不了的话，我再考虑加个回调事件

**Comment by hemengke1997** [comment]
closed on `2.5.0`
