### ISSUE TITLE
webpack使用有问题

### ISSUE THREAD

**Issue by AmoRunning** [hemengke1997/use-antd-resizable-header#22]
Error: Module "./@minko-fe/use-antd-resizable-header" does not exist in container.

**Comment by hemengke1997** [comment]
1. 安装的依赖版本是多少
2. 业务代码中是如何引入该依赖的

以上两点。截图或者copy代码给我看看，如果能给复现仓库最好不过了

**Comment by AmoRunning** [comment]
yarn add 引入依赖，使用方式是你readme中的例子。
"react-resizable": "^3.0.4",

**Comment by AmoRunning** [comment]
"@minko-fe/use-antd-resizable-header": "^2.4.1",

**Comment by hemengke1997** [comment]
例子中的使用方式是没有问题的

方便给个最小复现吗

**Comment by AmoRunning** [comment]
"umi": "^3.5.8",
    "umi-request": "^1.0.8",

使用的是MFSU
