### ISSUE TITLE
没有api让我修改表头数据吗

### ISSUE THREAD

**Issue by AmoRunning** [hemengke1997/use-antd-resizable-header#23]

**Comment by hemengke1997** [comment]
不需要通过 `use-antd-resizable-header` 修改表头数据

实际上你是想对antd的表格做操作，直接修改相应的state即可。
具体请参阅 antd table 的API

BTW，你昨天提到的 webpack 引入报错是什么原因？如何解决的？

**Comment by AmoRunning** [comment]
昨天的那个就是项目使用的是umi的mfsu方案搭建的，把mfsu关闭就可以了。

**Comment by AmoRunning** [comment]
我想修改表头哦，不是表内容

**Comment by AmoRunning** [comment]
现在的问题是，我的表头数据在异步请求函数里，hook没办法调用。（刚接触react）

**Comment by hemengke1997** [comment]
> 昨天的那个就是项目使用的是umi的mfsu方案搭建的，把mfsu关闭就可以了。

这个问题得去 umi 库提 issue


> 现在的问题是，我的表头数据在异步请求函数里，hook没办法调用。（刚接触react）

我的理解是你希望动态设置 `columns`。我的建议是把table组件作为子组件， columns作为 prop 从父组件传下去， 父组件中异步请求获取到表头后，set Columns 即可

**Comment by AmoRunning** [comment]
晓得了
