### ISSUE TITLE
提个用户体验的问题

### ISSUE THREAD

**Issue by henryzp** [hemengke1997/use-antd-resizable-header#24]
在拖的时候，如果按住鼠标，只会是head头在拖，而body没在拖。。

像react-base-table的这个示例：https://autodesk.github.io/react-base-table/examples/resizable

在拖动上，起码用户用得更舒服一些。。

**Comment by hemengke1997** [comment]
无法实现。antd表格本身的缺陷导致的。

**Comment by henryzp** [comment]
想了解一下，antd表格本身的缺陷是啥，学习下经验

**Comment by hemengke1997** [comment]
1. 去 antd 搜索表格拖拽相关的 issues， 可以了解到别人的痛点/官方的回复
2. 实践，使用拖拽库 配合 antd 实现你希望的效果
3. 了解 antd 表格源码

这三个做了你就知道是为什么了

**Comment by henryzp** [comment]
ok，感谢
