### ISSUE TITLE
希望resizableColumns 能从storage中取

### ISSUE THREAD

**Issue by mtiger95** [hemengke1997/use-antd-resizable-header#26]
1.因为项目有个需求是不仅拖拽宽度，还可拖拽列进行排序，同时将新顺序的columns缓存本地，但resizableColumns每次都重置了顺序再缓存到本地。

希望当缓存中有columns时，resizableColumns使用新顺序的缓存的columns。

2. 另外，请教一个问题，因为column中有reder函数，包括title也可以是一个ReactNode的函数式组件，使用JSON.stringify序列化时不会导致函数丢失或者异常行为吗？

**Comment by hemengke1997** [comment]
1. 我曾经实现过这个需求，不过已经从之前公司离职了..没代码了。  当时我是用的 pro-table 的列设置和本库配合实现的。
2. 不会，你试试就知道了

针对你的第一个问题哈，因为涉及到 break-change了，所以我不方便改动代码，如果你觉得改动此库代码可以满足你的需求的话，建议你fork一份。不过我认为你的业务代码里面修改就可以实现了。方便的话你可以贴一些关键代码出来我看看
