### ISSUE TITLE
defaultFilteredValue 失效了

### ISSUE THREAD

**Issue by liu-jane** [hemengke1997/use-antd-resizable-header#28]
给定的filter默认值未生效

**Comment by hemengke1997** [comment]
此hook没有处理过 `defaultFilteredValue`。
最好是给段代码我看看是你是怎么写的，您一句话我就得去翻 `antd(pro)` 的文档

**Comment by huakaii** [comment]
{
      title: "Name",
      dataIndex: "name",
      key: "name",
      width: 300,
      filters: [
        { text: "test", value: "1" },
        { text: "test2", value: "2" }
      ],
      defaultFilteredValue: ["1"]
    },

默认筛选1, 但是使用resizable-header后，功能失效

[codesandbox](https://codesandbox.io/s/unruffled-cdn-ocnejb?file=/src/App.tsx:766-997)

**Comment by hemengke1997** [comment]
fixed in `2.7.1`
