### ISSUE TITLE
显示滚动条的临界点有问题

### ISSUE THREAD

**Issue by Yang-yibu** [hemengke1997/use-antd-resizable-header#29]
这个问题是不是符合预期的？
![image](https://user-images.githubusercontent.com/23130670/201856356-6edf5858-3ab5-44c0-b088-fe9a2e947e4d.png)

**Comment by hemengke1997** [comment]
这是符合antd表格预期的

**Comment by hemengke1997** [comment]
Sorry，这是bug，可能跟 antd 版本有关，我今晚上处理一下

**Comment by hemengke1997** [comment]
codesanbox里面的例子不对，已修改
