### ISSUE TITLE
EditableProTable上使用时有bug

### ISSUE THREAD

**Issue by romez1991** [hemengke1997/use-antd-resizable-header#30]
![image](https://user-images.githubusercontent.com/13327337/202128498-5ea57a05-f88c-4d1e-bbdf-52e492e1393e.png)
选择一行进行操作时，会把选中的key值置空
![image](https://user-images.githubusercontent.com/13327337/202129021-48c36bc0-d991-4023-8538-e4e408c83b1a.png)
不使用这个hooks是正常的。
![image](https://user-images.githubusercontent.com/13327337/202129495-d17a57d9-5dc7-44f6-b694-49c9d0af4d3e.png)

https://codesandbox.io/s/jolly-greider-ff4916?file=/src/App.tsx

**Comment by hemengke1997** [comment]
复现打不开，我把代码复制到本地运行也报错了，是不是依赖不对？

**Comment by romez1991** [comment]
可能是我表达的不太清楚，选中一行是有selectedRowKeys值的，选中后把值放到state里面然后在对这行进行编辑或者删除的时候，state里面存的selectedRowKeys值会置空。麻烦大佬有空的时候再帮我看看T_T

**Comment by hemengke1997** [comment]
最好给个复现。
我刚试了：
1. 选中一行
2. 编辑选中的行，selecedRowKeys正常打印
3. 删除选中的行，selectedRowKeys正常打印
4. 添加一行，selectedRowKeys正常打印

https://stackblitz.com/edit/vitejs-vite-asy6mj?file=src%2Fmain.tsx,package.json,index.html,tsconfig.json,src%2FApp.tsx,vite.config.ts&terminal=dev

**Comment by romez1991** [comment]
线上代码工具不太会用，你把selectedRowKeys放到useState里面然后再打印，操作的时候会出问题

![image](https://user-images.githubusercontent.com/13327337/202342099-768e7921-2717-411c-834c-200454d595c0.png)

去掉拖拽功能后又是正常的

**Comment by hemengke1997** [comment]
你把代码拷一份出来吧，把业务代码去掉，留下 `选择` 相关的核心代码就行

**Comment by romez1991** [comment]
[demo.zip](https://github.com/hemengke1997/use-antd-resizable-header/files/10029072/demo.zip)

搞了个demo，yarn安装依赖应该能跑起来，大佬再给我看看吧

**Comment by hemengke1997** [comment]
🥲 没仔细看文档呀

https://github.com/hemengke1997/use-antd-resizable-header#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

> 若 column 有副作用，请把依赖项传入 useMemo deps 中

```typescript
const { components, resizableColumns, tableWidth } = useAntdResizableHeader<any>({
    columns: useMemo(() => columns, [selectedRowKeys])
});
```
