### ISSUE TITLE
columns是动态列useMemo，在后端api返回数据页面已经渲染了，怎么处理？

### ISSUE THREAD

**Issue by gametheworld** [hemengke1997/use-antd-resizable-header#31]

**Comment by hemengke1997** [comment]
后端返回的数据放在state里面，state是useMemo的依赖项

**Comment by gametheworld** [comment]
> 返回的数据放在state里

悬浮的会循环渲染，导致一直闪动

**Comment by gametheworld** [comment]
![image](https://user-images.githubusercontent.com/6021628/205880637-7125f996-3cca-4162-951c-e66c2356e1e8.png)

**Comment by hemengke1997** [comment]
```
columns: useMemo(()=>defaultColumns, [your state])
```

**Comment by gametheworld** [comment]
> useMemo(()=>defaultColumns, [your state])

没明白，调了一下午了，能否远程支持一波？

**Comment by gametheworld** [comment]
> 23536175

微信和qq都加您了
