### ISSUE TITLE
异步获取列，配合上持久化列宽会报错且不能正常渲染列表

### ISSUE THREAD

**Issue by xieguapi** [hemengke1997/use-antd-resizable-header#36]
**报错信息**
![image](https://user-images.githubusercontent.com/46696341/211232876-95bc135f-aabd-47ad-b745-68e923ef7dda.png)
**重现**
https://codesandbox.io/s/jolly-roentgen-bbq70k?file=/src/App.tsx

**Comment by hemengke1997** [comment]
谢谢反馈
我会尽快修复，可能是今天晚上

**Comment by hemengke1997** [comment]
fixed in `2.8.2`
