### ISSUE TITLE
异步渲染没问题之后，又发现了一个新问题

### ISSUE THREAD

**Issue by xieguapi** [hemengke1997/use-antd-resizable-header#38]
### 这边在对比得时候会导致异步获取的列宽度丢失，从而使异步的列不能拖动
![FB02A16F-0DEA-4309-BE25-31A41AE285DF](https://user-images.githubusercontent.com/46696341/211471648-4e146dd7-7fb9-4cbb-a7b0-b55dafb076ca.png)
![5D2AE013-9F1E-4a01-B77F-94A9F6DE8B01](https://user-images.githubusercontent.com/46696341/211471702-c2da5f80-02c2-4a6d-bbf7-e1fc2c7df18c.png)
![8E37BB15-329C-4496-B1EB-1EF81588D1D1](https://user-images.githubusercontent.com/46696341/211471714-3bd0e38a-4467-4201-9eba-baaacd738a67.png)
![118A306B-62CA-4459-B404-8782DA09FD4A](https://user-images.githubusercontent.com/46696341/211471729-7dab118c-b70c-4b79-b00a-aad10b5a538f.png)
### 尝试处理之后，可以正常渲染拖动了，但是会拖动结束后列表会抖动
![image](https://user-images.githubusercontent.com/46696341/211471966-9b5b8c9b-c044-43b5-b749-f9e8ef9f1f9b.png)
**抖动视频**
https://t.wss.ink/f/a81o6l9yit9

**Comment by xieguapi** [comment]
这个例子就能复现，然后本地存储里异步获取的列是没有宽度的，不能拖动
[use-antd-resizable-header](https://github.com/hemengke1997/use-antd-resizable-header)/[example](https://github.com/hemengke1997/use-antd-resizable-header/tree/master/example)/[src](https://github.com/hemengke1997/use-antd-resizable-header/tree/master/example/src)/CodeBox/

**Comment by xieguapi** [comment]
> 贴一下核心代码或者给个复现 : )

这个例子就能复现，然后本地存储里异步获取的列是没有宽度的，不能拖动
[use-antd-resizable-header](https://github.com/hemengke1997/use-antd-resizable-header)/[example](https://github.com/hemengke1997/use-antd-resizable-header/tree/master/example)/[src](https://github.com/hemengke1997/use-antd-resizable-header/tree/master/example/src)/CodeBox/

**Comment by hemengke1997** [comment]
fixed in `2.8.4`
