### ISSUE TITLE
无法控制表格列显示和隐藏

### ISSUE THREAD

**Issue by ningshunqiang** [hemengke1997/use-antd-resizable-header#40]
const { components, resizableColumns, tableWidth } = useAntdResizableHeader（.....）;

没有办法在外部改变 resizableColumns 的值，无法新增一个列对象

**Comment by ningshunqiang** [comment]
![image](https://user-images.githubusercontent.com/54874955/215987275-bc12b5ea-77d1-42d3-afea-865454cded74.png)

**Comment by hemengke1997** [comment]
如果可以提供一个复现，我可以最快修复

**Comment by ningshunqiang** [comment]
对不起，看错了，现在可以了
