### ISSUE TITLE
使用 ProTable 的列设置隐藏了列后拖拽的把手会错位

### ISSUE THREAD

**Issue by TunkShif** [hemengke1997/use-antd-resizable-header#44]
reproduction: [StackBlitz](https://stackblitz.com/edit/use-antd-resizable-header-demo-wz7fdj?file=src/App.tsx)

像下面的图中设置了某列为隐藏后，拖拽调整列宽的把手会错位

![image](https://user-images.githubusercontent.com/10807119/224216578-a44d6847-015d-4042-bd77-b854d6c5ec9a.png)

**Comment by hemengke1997** [comment]
前置条件：至少保持一列的宽度不定义。
`Company Name` 字段的width未定义，hide之后就不满足了前置条件了
