### ISSUE TITLE
自定义表头的场景下cache可能失效

### ISSUE THREAD

**Issue by wangweida** [hemengke1997/use-antd-resizable-header#51]
当可以自定义勾选表头时，由于每次onMount都重建了kvMap，可能导致之前拖拽的宽度会失效，比如以下场景，初始展示a与b表头，将a与b表头拖拽至一定宽度，取消勾选a与b然后再次勾选a与b，可以看到a表头保留了之前拖拽的宽度，但b被重置为初始宽度，合理的逻辑应该是a与b都保留之前的拖拽宽度或a与b都被重置为初始宽度

**Comment by hemengke1997** [comment]
你好，谢谢反馈。
由于场景特殊，我建议你fork一份仓库使用
感谢理解

**Comment by wangweida** [comment]
您好，我提了一个PR，能不能将kvMap放在useATRH中不用每次重建？
