### ISSUE TITLE
可不可以将kvMap放在useATRH中不用每次重建？

### ISSUE THREAD

**Issue by wangweida** [hemengke1997/use-antd-resizable-header#53]
_Originally posted by @wangweida in https://github.com/hemengke1997/use-antd-resizable-header/issues/51#issuecomment-1553941228_

您好，关于我说的那个场景，提了一个PR，我理解是不是可以kvMap不用每次都重建，留在useATRH中作为闭包就好可以了，因为确实好像不用每个表头onMount都重新建立一次kvMap把

**Comment by hemengke1997** [comment]
merged

**Comment by hemengke1997** [comment]
fixed in `2.8.13`

**Comment by wangweida** [comment]
> fixed in `2.8.13`

辛苦！
