### ISSUE TITLE
用pnpm安装然后打包完不生效是是原因，npm安装就可以

### ISSUE THREAD

**Issue by hulksqj** [hemengke1997/use-antd-resizable-header#55]
"antd": "^5.6.0",
    "typescript": "^5.0.2",
    "vite": "^4.3.9",
    "@minko-fe/use-antd-resizable-header": "^2.8.13",

**Comment by hulksqj** [comment]
试了好几遍， pnpm本地起来可以 打包部署到测试环境和正式环境就有问题，用npm install然后打包就可以 
大佬 这是为什么😂

**Comment by hemengke1997** [comment]
麻烦给个复现仓库

**Comment by hemengke1997** [comment]
你可以试试本地部署，构建之后使用 `vite preview` 开启本地服务预览
