### ISSUE TITLE
useGetDataIndexColumns.ts中getColumns增加list元素判空

### ISSUE THREAD

**Issue by SakuraiAiba** [hemengke1997/use-antd-resizable-header#57]
在chrome49中偶尔会出现报错Type error: cannot set property 'children' of null ，经定位发现是 useGetDataIndexColumns.ts 的getColumns方法中抛出的异常，是否可以对getColumns中的list的元素增加过滤判空处理，与useAntdResizableHeader.tsx中的getColumns中对list的处理一致？
![WechatIMG18](https://github.com/hemengke1997/use-antd-resizable-header/assets/13219028/f7700959-7f59-4611-8e19-c63f26869d22)
![WechatIMG19](https://github.com/hemengke1997/use-antd-resizable-header/assets/13219028/1d9fc2c9-693c-4f66-a94d-c8af65e5c87d)

**Comment by hemengke1997** [comment]
fixed in `2.8.14`
