### ISSUE TITLE
protable 中columns属性hideInTable 未true时，拖拽错位

### ISSUE THREAD

**Issue by AccOlaDe-peng** [hemengke1997/use-antd-resizable-header#58]
在```protable``` 中```columns ```开启```hideInTable```为```true``` ，会出现拖拽错位情况
![image](https://github.com/hemengke1997/use-antd-resizable-header/assets/24951225/456fe80c-e566-4148-a432-4095ed66e59e)

**Comment by hemengke1997** [comment]
请保持至少一列不设置宽度哈～
如果还是有问题的话，麻烦提供一个最小复现

**Comment by xiefengnian** [comment]
![image](https://github.com/hemengke1997/use-antd-resizable-header/assets/20136563/e55941c3-9f14-46f8-99c1-eb26161ef1b4)

我也遇到这个问题了，好像是在比较卡的时候，这时候 resizebox 修改了宽度，但是 column 没有

**Comment by hemengke1997** [comment]
> ![image](https://user-images.githubusercontent.com/20136563/279591163-e55941c3-9f14-46f8-99c1-eb26161ef1b4.png)
> 
> 我也遇到这个问题了，好像是在比较卡的时候，这时候 resizebox 修改了宽度，但是 column 没有

可以提供一个最小复现吗
