### ISSUE TITLE
添加对列头拖动松开后的回调事件

### ISSUE THREAD

**Issue by yang-xiaodong** [hemengke1997/use-antd-resizable-header#62]
Hi，

感谢对Antd生态做出的贡献，我们有一个需求，需要在松开列拖动的时候，将每一列的宽度实时保存到后端，现在没有合适的回调方法可以做到这一点，请问是否有计划对此特性提供支持？

Best regards!

**Comment by hemengke1997** [comment]
拖动结束后，把当前拖动的列以及宽度回调到上层，这些数据足够使用吗？

**Comment by yang-xiaodong** [comment]
感谢你的快速回复。

是的，列的引用对象和列宽度就够了。

**Comment by hemengke1997** [comment]
<img width="581" alt="image" src="https://github.com/hemengke1997/use-antd-resizable-header/assets/49073282/5097103b-7814-4412-9831-673d99209358">

这个参数应该满足你的需求
