### ISSUE TITLE
Uncaught TypeError: children.at is not a function at isSimpleChildren  at ResizableHeader at renderWithHooks（客户那里反应搜狗等低版本浏览器报children.at is not a function错误，更新到最新的搜狗浏览器后正常了，但是用户那里一般用的都不是最新版本的浏览器，这个问题可以解决吗）

### ISSUE THREAD

**Issue by keee1210** [hemengke1997/use-antd-resizable-header#64]
![微信图片_20231101111953](https://github.com/hemengke1997/use-antd-resizable-header/assets/44639815/1910cc83-6676-4fc8-8143-4b24fee193b4)
npm 8.1.2
node v16.13.2
搜狐浏览器版本 11.0.1.34700
@minko-fe/use-antd-resizable-header 2.8.13
IDE vscode

**Comment by hemengke1997** [comment]
fixed in `2.8.15`

**Comment by hemengke1997** [comment]
请问一下你用的什么框架，vite 还是 webpack？

**Comment by keee1210** [comment]
webpack craco

**Comment by keee1210** [comment]
你刚发布的版本我这边使用yarn 下载不了，最新只能下载到2.8.14

**Comment by keee1210** [comment]
![Uploading 微信图片_20231101114219.png…]()

**Comment by keee1210** [comment]
问题解决了，十分感谢

**Comment by keee1210** [comment]
低版本的360极速浏览器(13.5.2044.0) 报E.at is not a function，应该也是上面的兼容问题，麻烦能解决一下吗 我们这边很多使用360浏览器的这种
![微信图片_20231129165127](https://github.com/hemengke1997/use-antd-resizable-header/assets/44639815/bdc48a05-21f9-444d-8033-5aa055888989)
![微信图片_20231129165114](https://github.com/hemengke1997/use-antd-resizable-header/assets/44639815/fe618670-fecf-4574-88ea-95b7c82cc8c7)

**Comment by hemengke1997** [comment]
使用的什么版本呢

**Comment by keee1210** [comment]
2.8.15

**Comment by hemengke1997** [comment]
目前 2.9.0 打包后，库源码里面没有 `at` 方法

如果可以的话，麻烦你尝试升级

当然，如果想根绝此类问题发生，你可以在babel配置中添加 `Array.prototype.at` 的polyfill

**Comment by keee1210** [comment]
好的，谢谢
