### ISSUE TITLE
columns类型定义不匹配，能否与antd的columns类型保持一致

### ISSUE THREAD

**Issue by nenio1949** [hemengke1997/use-antd-resizable-header#67]
<img width="1027" alt="image" src="https://github.com/hemengke1997/use-antd-resizable-header/assets/37364223/c6aaa07c-8642-4b21-a0ed-0cf11f182f2b">

**Comment by hemengke1997** [comment]
可以，麻烦提供一个最小复现呢

**Comment by nenio1949** [comment]
> 可以，麻烦提供一个最小复现呢

就是我的columns的类型是antd提供的ColumnsType，而组件的columns的类型与antd提供的ColumnsType类型不一致，导致报类型不匹配的错误，图上很容易就能看出。还有就是设定的列宽小于实际渲染的列宽（列数量少且所有列的宽度和小于页面宽度），会出现收缩线与列之间的分割线无法对齐。

**Comment by hemengke1997** [comment]
麻烦提供一下复现，放github仓库就行

**Comment by hemengke1997** [comment]
Fixed in `2.9.0`
