### ISSUE TITLE
ellipsis的显示能否做的更完美一些

### ISSUE THREAD

**Issue by cyc2016** [hemengke1997/use-antd-resizable-header#68]
column中配置了`ellipsis: true`时，展示分两种情况：
1. 内容没有溢出，不显示省略号，鼠标悬浮无任何效果
2. 如果溢出了末尾就会有省略号并且鼠标悬浮上去有提示完整的内容

以上是期待中的展示效果，没问题。
接着拖拽调整列的宽度时，在情况1的前提下，当列宽足够小时，内容溢出，但只会显示省略号，鼠标悬浮上去没有提示，这里能否加上鼠标悬浮有tooltip效果的提示；在情况2的前提下，当列宽足够大，内容完整展示出来了，末尾的省略号消失了，但是鼠标悬浮上去还是有tooltip效果的提示，这种情况能否去掉

**Comment by hemengke1997** [comment]
你的期望是 tooltip是否展示由内容是否溢出控制吗？

**Comment by cyc2016** [comment]
> 你的期望是 tooltip是否展示由内容是否溢出控制吗？

是的老哥

**Comment by hemengke1997** [comment]
Fixed in `2.9.0`
