### ISSUE TITLE
columnRender事件问题

### ISSUE THREAD

**Issue by zwg890919** [hemengke1997/use-antd-resizable-header#7]
我遇到个小问题   如果在render中绑定了点击事件。点击事件使用了useState绑定的数据  当触发点击事件时   绑定的数据并不会显示最新的内容  类似于

`const [ifWorkTime, setifWorkTime] = useState(true);
  let columns = [ {
         title: '本期',
          dataIndex: 'currentBillAmount',
          key: 'currentBillAmount',
          align: 'center',
          render: (text, row) => (
            <div
              className="text-blue"
              onClick={() => {
                goDetailPage(row);
              }}>
              {text}
            </div>
          ),}]

const goDetailPage = (rowData, type) => {console.log(ifWorkTime)}
`

**Comment by hemengke1997** [comment]
这是个bug，我没有考虑到columns中有副作用的情况。
1.5.2 中，每次render，会做深比较，对于函数，是比较函数字符串，所以未触发更新。
如果不阻止render，会造成循环无限render。即：组件每次render => 导致columns引用变化 => 导致use-antd-resiable-header渲染 => 导致组件render。
目前有两个想法
1. 使用 React.memo包裹columns，明确columns在哪些情况下render
2. useARH({ refreshDeps: [依赖项] })

这两种方法都需要开发者明确哪些情况下需要重新渲染，增加了开发者的心智负担。但目前没有想到完美的解决方案。
我打算使用方案2，临时解决您现在遇到的问题

**Comment by hemengke1997** [comment]
升级至 1.5.3
使用方法： 
```
useARH({ columns, refreshDeps: [ ifWorkTime ] })
```

**Comment by zwg890919** [comment]
之前试过方法一  并没有成功更新  我试下方法二

**Comment by hemengke1997** [comment]
先升级哈 老哥。
我采用的方案2，所以使用React.memo没有效果

**Comment by zwg890919** [comment]
嗯  使用方法二已解决。辛苦了。非常感谢
