### ISSUE TITLE
低版本的360极速浏览器(13.5.2044.0) 报E.at is not a function，应该也是上面的兼容问题，麻烦能解决一下吗 我们这边很多使用360浏览器的这种

### ISSUE THREAD

**Issue by keee1210** [hemengke1997/use-antd-resizable-header#70]
低版本的360极速浏览器(13.5.2044.0) 报E.at is not a function，应该也是上面的兼容问题，麻烦能解决一下吗 我们这边很多使用360浏览器的这种
![微信图片_20231129165127](https://github.com/hemengke1997/use-antd-resizable-header/assets/44639815/bdc48a05-21f9-444d-8033-5aa055888989)
![微信图片_20231129165114](https://github.com/hemengke1997/use-antd-resizable-header/assets/44639815/fe618670-fecf-4574-88ea-95b7c82cc8c7)

_Originally posted by @keee1210 in https://github.com/hemengke1997/use-antd-resizable-header/issues/64#issuecomment-1831475838_

**Comment by hemengke1997** [comment]
trace #64
close
