### ISSUE TITLE
onHeaderCell属性无法生效

### ISSUE THREAD

**Issue by LonelyFanhe** [hemengke1997/use-antd-resizable-header#73]
复现链接：https://stackblitz.com/edit/use-antd-resizable-header-demo-arqflb?file=src%2FApp.tsx
问题：
![image](https://github.com/hemengke1997/use-antd-resizable-header/assets/17561538/6193bccd-1998-4541-8485-36b11892dec0)
期望：
![image](https://github.com/hemengke1997/use-antd-resizable-header/assets/17561538/9a99756c-acc9-4e1a-990a-6d106758a2c4)

**Comment by hemengke1997** [comment]
fixed in `2.9.1`
