### ISSUE TITLE
React17报错  Can't resolve 'react/jsx-runtime'

### ISSUE THREAD

**Issue by LitKeung** [hemengke1997/use-antd-resizable-header#74]
![image](https://github.com/hemengke1997/use-antd-resizable-header/assets/17907444/73fd6f38-5c77-4577-adcc-a9ff1a05cba0)
![image](https://github.com/hemengke1997/use-antd-resizable-header/assets/17907444/b1e2215a-d33b-4b6b-94e0-83244e20a0d3)

**Comment by hemengke1997** [comment]
tsconfig中配置jsx:react-jsx
若不行的话我这边再做更新

**Comment by hemengke1997** [comment]
fixed in `2.9.2`

**Comment by hana2644** [comment]
配置了怎么还是报错呢
<img width="855" alt="企业微信截图_17304325504534" src="https://github.com/user-attachments/assets/4405558d-dad6-4d02-983e-53f6c0a4372f">
