### ISSUE TITLE
columns副作用

### ISSUE THREAD

**Issue by candy4290** [hemengke1997/use-antd-resizable-header#78]
通过memo包裹，利用columns的副作用。如果此时，我自己实现重置列宽的方法，能否通过将columns中每一项的width更新,达到重置列宽的需求？目前发现这样做，没有效果。求助～

**Comment by hemengke1997** [comment]
有提供 `resetColumns` 方法来重置列宽

**Comment by candy4290** [comment]
> 有提供 `resetColumns` 方法来重置列宽

嗯嗯，我使用缓存来持久化，发现我调整后，刷新整个页面。这时候调用这个函数是无法重置到最初状态的。我需要重置到最开始进入页面的列宽～～～
所以就想着试试利用副作用能否达到效果。
作者大大帮忙看下，虽然我现在通过一些旁门左道也实现了这个功能，但是写的太绕了～～～

**Comment by hemengke1997** [comment]
我没理解到你的需求，麻烦你理一下 重新描述哈

**Comment by candy4290** [comment]
> 我没理解到你的需求，麻烦你理一下 重新描述哈
假设最开始列宽状态为A。调整列宽，且通过配置columnsState持久化。问题是我调整列宽后，F5刷新页面，此时调用resetColumns，不会恢复到最开始的列宽状态A。
不知道我这么说，可否理解。或者我的需求是否合理？
