### ISSUE TITLE
期望提供自定义渲染拖拽handler

### ISSUE THREAD

**Issue by lk0606** [hemengke1997/use-antd-resizable-header#80]
将 图二圈起来代码，作为props传入即可
![image](https://github.com/hemengke1997/use-antd-resizable-header/assets/43233310/2daa4d96-43b5-4c34-be93-7ae90597be3f)
![image](https://github.com/hemengke1997/use-antd-resizable-header/assets/43233310/c70660c3-fe9d-4aee-836c-c021ef3da820)

**Comment by hemengke1997** [comment]
欢迎PR～

**Comment by lk0606** [comment]
> 欢迎PR～

已经写好了。
![image](https://github.com/hemengke1997/use-antd-resizable-header/assets/43233310/e11d73fa-ba86-4f24-8e7a-fcc6d1647a2b)
![image](https://github.com/hemengke1997/use-antd-resizable-header/assets/43233310/7221a6fb-318e-403c-95e7-25693a34ba28)
