### ISSUE TITLE
Header Resizing Issue: Insufficient Adjustment with Mouse

### ISSUE THREAD

**Issue by mahiraltinkaya** [hemengke1997/use-antd-resizable-header#84]
Hello, thank you for this valuable library. I am integrating it freshly. I have a small issue. My table consists of 45 columns. I have 5 fixed columns, and I have set widths for all of them. Besides these, there are 10-15 more columns with widths. The problem is when I try to resize a column header by dragging my mouse by 200-300 pixels, the header only enlarges or shrinks by about 50 pixels. As I continue dragging the mouse, this number increases to 60-70 pixels, but it's not working as expected. Sometimes it works perfectly fine, though. Could you provide assistance with this issue? Also, When I narrow the headers, the 'resizable-line' area moves along with the mouse and is visible. However, when I expand them, only the mouse cursor appears as 'ew-resize,' but the 'resizable-line' area is not displayed.

![image](https://github.com/hemengke1997/use-antd-resizable-header/assets/25014707/497c9213-3b00-4d25-86c1-6651f05e61a8)

**Comment by bebossi** [comment]
I'm facing the same problem, were you able to fix it?

**Comment by mahiraltinkaya** [comment]
> I'm facing the same problem, were you able to fix it?

Hey bebossi, unfortunately I can't fix it. Therefore, I am using TanStack Table for the solution.

**Comment by hemengke1997** [comment]
Please provide online reproduction
