### ISSUE TITLE
Antd Table  5.13.0 开始支持hidden属性，即隐藏列，表格宽度计算未考虑hidden

### ISSUE THREAD

**Issue by haiing** [hemengke1997/use-antd-resizable-header#86]
Antd Table  5.13.0 开始支持hidden属性，即隐藏列，和ProTable的hideInTable相同，

在计算表格宽度是，ProTable考虑了hideInTable, 但Table的hidden属性未考虑，希望尽快对齐这两个属性

**Comment by huxianghe** [comment]
上面一楼的听起来阿里味挺重啊，开源的被你当作 api 来考核？hidden 属性未做兼容，自己不会转换下？

**Comment by hemengke1997** [comment]
> 上面一楼的听起来阿里味挺重啊，开源的被你当作 api 来考核？hidden 属性未做兼容，自己不会转换下？

没事没事，我最近在忙其他项目，暂时没有精力更新这个，这几天抽空更新下
