### ISSUE TITLE
项目运行报错

### ISSUE THREAD

**Issue by yxf18** [hemengke1997/use-antd-resizable-header#87]
> use-antd-resizable-header@2.9.5 build D:\源码\use-antd-resizable-header
> rimraf dist && tsup

CLI Building entry: ./src/index.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v7.2.0
CLI Using tsup config: D:\源码\use-antd-resizable-header\tsup.config.ts
CLI Target: es2015
ESM Build start
CJS Build start
X [ERROR] Unexpected "%"

    src/index.ts:1:0:
      1 │ %TSD-Header-###%&���+��+Ȕ�)��@�����ZPY��\��,4&�fGhx;���qr�ai���*��' �8�Θ��޾�~�T�u.�TB�O�{r�...
        ╵ ^X

[ERROR] Unexpected "%"

    src/index.ts:1:0:
      1 │ %TSD-Header-###%&���+��+Ȕ�)��@�����ZPY��\��,4&�fGhx;���qr�ai���*��' �8�Θ��޾�~�T�u.�TB�O�{r�...
        ╵ ESM Build failed
^

Error: Build failed with 1 error:
src/index.ts:1:0: ERROR: Unexpected "%"

**Comment by hemengke1997** [comment]
<img width="774" alt="image" src="https://github.com/hemengke1997/use-antd-resizable-header/assets/49073282/5ed67e60-8572-4723-b8e7-c827cc8f91d0">

可能跟目录名中有中文有关？尝试把中文改成英文试试
