### ISSUE TITLE
defaultWidth 不生效

### ISSUE THREAD

**Issue by Samxjq** [hemengke1997/use-antd-resizable-header#88]
没有width不可拖动列添加属性defaultWidth无效

**Comment by hemengke1997** [comment]
请贴一下配置代码

**Comment by Samxjq** [comment]
import { Space, Table, Tag } from 'antd'
import React, { useMemo, useReducer, useState } from 'react'
import { useAntdResizableHeader } from 'use-antd-resizable-header'

const data = [
  {
    key: '1',
    name: 'John Brown',
    age: 32,
    address: 'New York No. 1 Lake Park',
    tags: ['nice', 'developer'],
  },
  {
    key: '2',
    name: 'Jim Green',
    age: 42,
    address: 'London No. 1 Lake Park',
    tags: ['loser'],
  },
  {
    key: '3',
    name: 'Joe Black',
    age: 32,
    address: 'Sidney No. 1 Lake Park',
    tags: ['cool', 'teacher'],
  },
]

const App = () => {
  const [, forceRender] = useReducer((s) => s + 1, 0)
  const [deps, setDeps] = useState(0)

  const columns = [
    {
      title: 'Name',
      dataIndex: 'name',
      key: 'name',
      width: 500,
      ellipsis: true,
      render: (text) => (
        <a onClick={() => setDeps((t) => t + 1)}>
          {text}
          {deps}
        </a>
      ),
    },
    {
      title: 'Age',
      dataIndex: 'age',
      key: 'age',
      ellipsis: true,
      width: 500,
    },
    {
      title: 'Address',
      dataIndex: 'address',
      key: 'address',
      ellipsis: true,
      width: 500,
    },
    {
      title: 'Tags',
      key: 'tags',
      dataIndex: 'tags',
      width: 500,
      ellipsis: true,
      render: (tags) => (
        <>
          {tags.map((tag) => {
            let color = tag.length > 5 ? 'geekblue' : 'green'
            if (tag === 'loser') {
              color = 'volcano'
            }
            return (
              <Tag color={color} key={tag}>
                {tag.toUpperCase()}
              </Tag>
            )
          })}
        </>
      ),
    },
    {
      title: 'render',
      key: 'action',
      defaultWidth: 500,
      render: (text, record) => (
        <Space size='middle'>
          <a>Invite {record.name}</a>
          <a
            onClick={() => {
              forceRender()
              alert('render')
            }}
          >
            render
          </a>
        </Space>
      ),
    },
  ]

  const { components, resizableColumns, tableWidth } = useAntdResizableHeader({
    columns: useMemo(() => columns, [deps]),
  })

  return <Table columns={resizableColumns} components={components} dataSource={data} scroll={{ x: tableWidth }} />
}

export default App

**Comment by Molly29** [comment]
请问有解决方法了吗？

**Comment by Samxjq** [comment]
博主更新了版本，试试


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年08月09日 15:14 |
| 收件人 | hemengke1997/use-antd-resizable-header ***@***.***> |
| 抄送人 | Samxjq ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [hemengke1997/use-antd-resizable-header] defaultWidth 不生效 (Issue #88) |

请问有解决方法了吗？

**Comment by wujiali96** [comment]
3.2最新版本同样遇到这个问题，怎么解？？？没有width不可拖动列添加属性defaultWidth无效
