### ISSUE TITLE
ProTable  使用过程中，clss 并没有加入插件样式，导致拖拽没生效

### ISSUE THREAD

**Issue by wx9999** [hemengke1997/use-antd-resizable-header#90]
ProTable  使用过程中，clss 并没有加入插件样式，导致拖拽没生效
<img width="792" alt="image" src="https://github.com/hemengke1997/use-antd-resizable-header/assets/42061047/a7b5246f-9a9b-4ebc-a1e9-13101664fc10">
<img width="444" alt="image" src="https://github.com/hemengke1997/use-antd-resizable-header/assets/42061047/07779b83-9353-43e0-aad8-ebd1ebc72cfa">
<img width="755" alt="image" src="https://github.com/hemengke1997/use-antd-resizable-header/assets/42061047/d3eaa5da-2834-4766-ac05-9c3f2a603f8b">
<img width="420" alt="image" src="https://github.com/hemengke1997/use-antd-resizable-header/assets/42061047/2dc4ee6a-b2bf-4219-95de-9c684053870b">
请问应该怎么解决呢

**Comment by LeleDallas** [comment]
Did you pass a `width` in your ProColumns object?

**Comment by wx9999** [comment]
> Did you pass a `width` in your ProColumns object?
并没有定义宽度  
<img width="530" alt="image" src="https://github.com/hemengke1997/use-antd-resizable-header/assets/42061047/d56f3219-e3a0-4097-b327-1afa2aa8e54e">

**Comment by LeleDallas** [comment]
Check the [README.md](https://github.com/hemengke1997/use-antd-resizable-header/blob/master/README.md) file and also this comment https://github.com/hemengke1997/use-antd-resizable-header/issues/79#issuecomment-1950741956 from the owner

**Comment by hemengke1997** [comment]
请贴一下columns的代码
